# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33bbb588623e5278ad7d74b59f4b4c289b128eda225635a6d43508903b0d5c9f01fa961a45f71e819fa68d579fb63eeecde199b5a95acd02aee8f16c8456d74b

test:
  secret_key_base: d45acbd0652dddc6017221fb06d1f4ac8e7402333f5b0e0d9ec640b28492fa18e7341d27ae4d7bf44e3132b620c8c8e6c7b87e2270a16d0a417344d46e3936d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
